// src/lib/components/ScheduleRow.svelte
<script type="ts">
    import type { DisplayCL } from '$types';
    import autoAnimate from '@formkit/auto-animate';
    import { format, isAfter, parse } from 'date-fns';
    import { onMount } from 'svelte';
    import { slide } from 'svelte/transition';
    import Fa from 'svelte-fa';
    import Countdown from './Countdown.svelte';
    import {
        faCircle,
        faMinus,
        faPlus,
        faSun,
    } from '@fortawesome/free-solid-svg-icons';
    import DateBar from './DateBar.svelte';
    let hide = true;
    export let displayDate: Date;
    export let cls: DisplayCL;
    export let index: number;
    let currentDate = new Date();
    onMount(() => {
        let x = setInterval(() => {
            currentDate = new Date();
        }, 1000);
        return () => {
            clearInterval(x);
        };
    });

    $: startTime = parse(cls.start, 'HH:mm', displayDate);
    $: endTime = parse(cls.end, 'HH:mm', displayDate);
    $: isNow = isAfter(currentDate, startTime) && isAfter(endTime, currentDate);
    $: isOdd = index % 2 == 1;
</script>

<div
    class={(isOdd ? 'bg-base-200' : 'bg-base-300') + ' cursor-pointer'}
    on:click={() => {
        hide = !hide;
    }}
    on:keydown
>
    <div class="flex flex-row justify-evenly items-center">
        <div class="px-2" />
        <Fa icon={faCircle} class={!isNow ? 'invisible' : ''} />
        <div
            class="w-full h-fit grid max-md:grid-cols-2 gap-2 px-1 text-center grid-cols-4 grid-rows-1 place-content-center justify-around justify-items-center"
        >
            <div>
                <strong>
                    {format(startTime, 'h:mm')} - {format(endTime, 'h:mm')}
                </strong>
            </div>
            <div>
                <strong>{cls.name}</strong>
            </div>
            <div class="max-md:hidden">
                <strong>{cls.teacher.name}</strong>
            </div>
            <div class="max-md:hidden" class:hidden={cls.room == ''}>
                <strong>{cls.room}</strong>
            </div>
        </div>
        <Fa icon={hide ? faPlus : faMinus} />
        <div class="px-2" />
    </div>
    {#if !hide}
        <div transition:slide|local class="bottom flex flex-col">
            <div>Details about class, grades, and other stuff here</div>
            <div>
                <strong> Current Grade A+ (todo) </strong>
            </div>
            <div>
                <strong>
                    <a href={'mailto:' + cls.teacher.email}>
                        Email {cls.teacher.name}
                    </a>
                </strong>
            </div>
            <div class:hidden={cls.room == ''}>
                <strong>Room {cls.room}</strong>
            </div>
            <div>
                {#if isAfter(currentDate, endTime)}
                    Class Ended
                {:else}
                    <strong>{isNow ? 'Ending' : 'Beginning'} in</strong>
                    <Countdown destDate={isNow ? endTime : startTime} />
                {/if}
            </div>
            <div>
                {#if isNow}
                    <DateBar startDate={startTime} destDate={endTime} />
                {/if}
            </div>
        </div>
    {/if}
</div>

// src/pages/schedule2/ScheduleRow.tsx
import { Button, Stack } from '@mui/material';
import { format, isAfter, parse } from 'date-fns';
import { useState } from 'react';
import Grid2 from '@mui/material/Unstable_Grid2';

export default function ScheduleRow(props: { alt: boolean; data: { name: string; teacher: string; room: string; start: string; end: string } }) {
    const [hide, setHide] = useState(true);
    const currentDate = new Date();
    const displayDate = new Date();
    const startTime = parse(props.data.start, 'HH:mm', displayDate);
    const endTime = parse(props.data.end, 'HH:mm', displayDate);
    const isNow = isAfter(currentDate, startTime) && isAfter(endTime, currentDate);

    return (
        <div className={props.alt ? 'scheduleRowAlternate' : ''}>
            <Grid2
                container
                spacing={0}
                onClick={() => {
                    setHide(!hide);
                }}
            >
                <Grid2 xs></Grid2>
                <Grid2 xs={2}>
                    <div>
                        <strong>
                            {format(startTime, 'h:mm')} - {format(endTime, 'h:mm')}
                        </strong>
                    </div>
                </Grid2>
                <Grid2 xs={2}>
                    <div>
                        <strong>{props.data.name}</strong>
                    </div>
                </Grid2>
                <Grid2 xs={2}>
                    <div>
                        <strong>teacher name</strong>
                    </div>
                </Grid2>
                <Grid2 xs={2}>
                    <div>
                        <strong>room number</strong>
                    </div>
                </Grid2>
                <Grid2 xs></Grid2>
            </Grid2>
            {!hide ? (
                <div>
                    <div>Details about class, grades, and other stuff here</div>
                    <div>
                        <strong> Current Grade A+ (todo) </strong>
                    </div>
                    <div>
                        <strong>
                            <a href={'mailto:' + 'teacher email'}>Email teacher name</a>
                        </strong>
                    </div>
                    <div>
                        <strong>Room number</strong>
                    </div>
                    <div>
                        {isAfter(currentDate, endTime) ? (
                            <strong>Class Ended</strong>
                        ) : (
                            <div>
                                <strong>{isNow ? 'Ending' : 'Beginning'} in</strong>
                                {/* <Countdown destDate={isNow ? endTime : startTime} /> */}
                            </div>
                        )}
                    </div>
                    <div>{isNow ? <div>progress bar{/*<DateBar startDate={startTime} destDate={endTime} /> */}</div> : ''}</div>
                </div>
            ) : (
                ''
            )}
        </div>
    );
}
