// src/lib/components/Countdown.svelte
<script type="ts">
    import { formatDuration, intervalToDuration } from 'date-fns';
    import { onMount } from 'svelte';

    let now = new Date();
    onMount(() => {
        let x = setInterval(() => {
            now = new Date();
        }, 100);
        return () => {
            clearInterval(x);
        };
    });
    export let destDate: Date;
    $: message = formatDuration(
        intervalToDuration({
            start: now,
            end: destDate,
        })
    );
</script>

<div>{message}</div>

// src/pages/schedule/Countdown.tsx
import { useInterval } from 'react-use';
import { Time, timeToDate } from '../../types';
import { useState } from 'preact/hooks';
import { formatDuration, intervalToDuration } from 'date-fns';

export default function Countdown(props: { destDate: Time }) {
    const [time, setTime] = useState('');
    useInterval(() => {
        const now = new Date();
        const dest = timeToDate(props.destDate);
        const duration = intervalToDuration({ start: now, end: dest });
        setTime(formatDuration(duration));
    }, 1000);
    return <div>{time}</div>;
}
